wandb_version: 1

slurm:
  desc: null
  value:
    LAUNCHER_ROOT: /srv/flash1/pputta7/.experiments
    CONF: /etc/slurm-llnl/slurm.conf
    PRIO_PROCESS: '0'
    UMASK: '0022'
    CLUSTER_NAME: skynet
    SUBMIT_DIR: /nethome/pputta7
    SUBMIT_HOST: sky2
    JOB_NAME: gpushell
    JOB_CPUS_PER_NODE: '128'
    NTASKS: '1'
    NPROCS: '1'
    CPUS_PER_TASK: '128'
    JOB_ID: '641639'
    JOBID: '641639'
    STEP_ID: '0'
    STEPID: '0'
    NNODES: '1'
    JOB_NUM_NODES: '1'
    NODELIST: clippy
    JOB_PARTITION: short
    TASKS_PER_NODE: '1'
    SRUN_COMM_PORT: '7135'
    PTY_PORT: '7134'
    PTY_WIN_COL: '237'
    PTY_WIN_ROW: '51'
    JOB_UID: '1125542'
    JOB_USER: pputta7
    JOB_ACCOUNT: cvmlp-lab
    JOB_QOS: normal
    WORKING_CLUSTER: skynet:marvin:6817:9216:109
    JOB_NODELIST: clippy
    STEP_NODELIST: clippy
    STEP_NUM_NODES: '1'
    STEP_NUM_TASKS: '1'
    STEP_TASKS_PER_NODE: '1'
    STEP_LAUNCHER_PORT: '7135'
    SRUN_COMM_HOST: 130.207.124.6
    STEP_GPUS: 0,1,2,3,4,5,6,7
    TOPOLOGY_ADDR: clippy
    TOPOLOGY_ADDR_PATTERN: node
    CPUS_ON_NODE: '128'
    CPU_BIND: quiet,mask_cpu:0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF
    CPU_BIND_LIST: '0xFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFFF'
    CPU_BIND_TYPE: 'mask_cpu:'
    CPU_BIND_VERBOSE: quiet
    TASK_PID: '2546661'
    NODEID: '0'
    PROCID: '0'
    LOCALID: '0'
    LAUNCH_NODE_IPADDR: 130.207.124.6
    GTIDS: '0'
    JOB_GID: '2626'
habitat:
  desc: null
  value:
    seed: 100
    env_task: GymHabitatEnv
    env_task_gym_dependencies: []
    env_task_gym_id: ''
    environment:
      max_episode_steps: 500
      max_episode_seconds: 10000000
      iterator_options:
        cycle: true
        shuffle: true
        group_by_scene: true
        num_episode_sample: -1
        max_scene_repeat_episodes: -1
        max_scene_repeat_steps: 10000
        step_repetition_range: 0.2
    simulator:
      type: Sim-v0
      forward_step_size: 0.25
      turn_angle: 30
      create_renderer: false
      requires_textures: true
      auto_sleep: false
      step_physics: true
      concur_render: false
      needs_markers: true
      update_articulated_agent: true
      scene: data/scene_datasets/habitat-test-scenes/van-gogh-room.glb
      scene_dataset: default
      additional_object_paths: []
      seed: ${habitat.seed}
      default_agent_id: 0
      debug_render: false
      debug_render_articulated_agent: false
      kinematic_mode: false
      should_setup_semantic_ids: true
      debug_render_goal: true
      robot_joint_start_noise: 0.0
      ctrl_freq: 120.0
      ac_freq_ratio: 4
      load_objs: true
      hold_thresh: 0.15
      grasp_impulse: 10000.0
      agents:
        main_agent:
          height: 1.5
          radius: 0.1
          grasp_managers: 1
          sim_sensors:
            rgb_sensor:
              type: HabitatSimRGBSensor
              height: 480
              width: 640
              position:
              - 0.0
              - 1.25
              - 0.0
              orientation:
              - 0.0
              - 0.0
              - 0.0
              hfov: 90
              sensor_subtype: PINHOLE
              noise_model: None
              noise_model_kwargs: {}
            depth_sensor:
              type: HabitatSimDepthSensor
              height: 480
              width: 640
              position:
              - 0.0
              - 1.25
              - 0.0
              orientation:
              - 0.0
              - 0.0
              - 0.0
              hfov: 90
              sensor_subtype: PINHOLE
              noise_model: None
              noise_model_kwargs: {}
              min_depth: 0.0
              max_depth: 10.0
              normalize_depth: true
          is_set_start_state: false
          start_position:
          - 0.0
          - 0.0
          - 0.0
          start_rotation:
          - 0.0
          - 0.0
          - 0.0
          - 1.0
          joint_start_noise: 0.1
          joint_start_override: null
          articulated_agent_urdf: data/robots/hab_fetch/robots/hab_fetch.urdf
          articulated_agent_type: FetchRobot
          ik_arm_urdf: data/robots/hab_fetch/robots/fetch_onlyarm.urdf
          motion_data_path: ''
      agents_order:
      - main_agent
      default_agent_navmesh: true
      navmesh_include_static_objects: false
      habitat_sim_v0:
        gpu_device_id: 0
        gpu_gpu: false
        allow_sliding: true
        frustum_culling: true
        enable_physics: false
        physics_config_file: ./data/default.physics_config.json
        leave_context_with_background_renderer: false
        enable_gfx_replay_save: false
      ep_info: null
      object_ids_start: 100
      renderer:
        enable_batch_renderer: false
        composite_files: null
        classic_replay_renderer: false
    task:
      physics_target_sps: 60.0
      reward_measure: distance_to_goal_reward
      success_measure: spl
      success_reward: 2.5
      slack_reward: -0.01
      end_on_success: true
      type: Nav-v0
      lab_sensors:
        imagegoal_sensor:
          type: ImageGoalSensor
      measurements:
        distance_to_goal:
          type: DistanceToGoal
          distance_to: POINT
        success:
          type: Success
          success_distance: 0.2
        spl:
          type: SPL
        distance_to_goal_reward:
          type: DistanceToGoalReward
        top_down_map:
          type: TopDownMap
          max_episode_steps: 1000
          map_padding: 3
          map_resolution: 1024
          draw_source: true
          draw_border: true
          draw_shortest_path: true
          draw_view_points: true
          draw_goal_positions: true
          draw_goal_aabbs: true
          fog_of_war:
            draw: true
            visibility_dist: 5.0
            fov: 90
      rank0_env0_measure_names:
      - habitat_perf
      rank0_measure_names: []
      goal_sensor_uuid: pointgoal
      count_obj_collisions: true
      settle_steps: 5
      constraint_violation_ends_episode: true
      constraint_violation_drops_object: false
      force_regenerate: false
      should_save_to_cache: false
      object_in_hand_sample_prob: 0.167
      min_start_distance: 3.0
      render_target: true
      physics_stability_steps: 1
      num_spawn_attempts: 200
      spawn_max_dist_to_obj: 2.0
      base_angle_noise: 0.523599
      recep_place_shrink_factor: 0.8
      ee_sample_factor: 0.2
      ee_exclude_region: 0.0
      base_noise: 0.05
      spawn_region_scale: 0.2
      joint_max_impulse: -1.0
      desired_resting_position:
      - 0.5
      - 0.0
      - 1.0
      use_marker_t: true
      cache_robot_init: false
      success_state: 0.0
      should_enforce_target_within_reach: false
      task_spec_base_path: habitat/task/rearrange/pddl/
      task_spec: ''
      pddl_domain_def: replica_cad
      obj_succ_thresh: 0.3
      enable_safe_drop: false
      art_succ_thresh: 0.15
      robot_at_thresh: 2.0
      actions:
        stop:
          type: StopAction
          agent_index: 0
        move_forward:
          type: MoveForwardAction
          agent_index: 0
          tilt_angle: 15
        turn_left:
          type: TurnLeftAction
          agent_index: 0
          tilt_angle: 15
        turn_right:
          type: TurnRightAction
          agent_index: 0
          tilt_angle: 15
    dataset:
      type: PointNav-v1
      split: train
      scenes_dir: data/scene_datasets
      content_scenes:
      - 00744-1S7LAXRdDqK
      data_path: data/datasets/imagenav/hm3d/v1/{split}/{split}.json.gz
    gym:
      obs_keys: null
      action_keys: null
      achieved_goal_keys: []
      desired_goal_keys: []
habitat_baselines:
  desc: null
  value:
    evaluate: false
    trainer_name: ppo
    updater_name: PPO
    distrib_updater_name: DDPPO
    torch_gpu_id: 0
    tensorboard_dir: tb
    writer_type: tb
    video_dir: video_dir
    video_fps: 10
    test_episode_count: -1
    eval_ckpt_path_dir: data/checkpoints
    num_environments: 10
    num_processes: -1
    rollout_storage_name: RolloutStorage
    checkpoint_folder: data/checkpoints
    num_updates: 10000
    num_checkpoints: 10
    checkpoint_interval: -1
    total_num_steps: -1.0
    log_interval: 10
    log_file: train.log
    force_blind_policy: false
    verbose: true
    vector_env_factory:
      _target_: habitat_baselines.common.HabitatVectorEnvFactory
    eval_keys_to_include_in_name: []
    force_torch_single_threaded: false
    wb:
      project_name: lmnav
      entity: ''
      group: train
      run_name: lmnav_imagenav
    load_resume_state_config: true
    eval:
      split: val
      use_ckpt_config: true
      should_load_ckpt: true
      evals_per_ep: 1
      video_option: []
      extra_sim_sensors: {}
    profiling:
      capture_start_step: -1
      num_steps_to_capture: -1
    should_log_single_proc_infos: false
    on_save_ckpt_callback: null
    rl:
      agent:
        type: SingleAgentAccessMgr
      preemption:
        append_slurm_job_id: false
        save_resume_state_interval: 100
        save_state_batch_only: false
      policy:
        name: PointNavResNetPolicy
        action_distribution_type: categorical
        action_dist:
          use_log_std: true
          use_softplus: false
          std_init: ???
          log_std_init: 0.0
          use_std_param: false
          clamp_std: true
          min_std: 1.0e-06
          max_std: 1
          min_log_std: -5
          max_log_std: 2
          action_activation: tanh
          scheduled_std: false
        obs_transforms:
          resize_shortest_edge:
            type: ResizeShortestEdge
            size: 120
            channels_last: true
            trans_keys:
            - rgb
            - depth
            - imagegoal
            semantic_key: semantic
        hierarchical_policy: ???
      ppo:
        clip_param: 0.2
        ppo_epoch: 4
        num_mini_batch: 2
        value_loss_coef: 0.5
        entropy_coef: 0.01
        lr: 0.00025
        eps: 1.0e-05
        max_grad_norm: 0.5
        num_steps: 5
        use_gae: true
        use_linear_lr_decay: false
        use_linear_clip_decay: false
        gamma: 0.99
        tau: 0.95
        reward_window_size: 50
        use_normalized_advantage: false
        hidden_size: 512
        entropy_target_factor: 0.0
        use_adaptive_entropy_pen: false
        use_clipped_value_loss: true
        use_double_buffered_sampler: false
      ddppo:
        sync_frac: 0.6
        distrib_backend: NCCL
        rnn_type: GRU
        num_recurrent_layers: 1
        backbone: resnet18
        pretrained_weights: data/ddppo-models/gibson-2plus-resnet50.pth
        pretrained: false
        pretrained_encoder: false
        train_encoder: true
        reset_critic: true
        force_distributed: false
      ver:
        variable_experience: true
        num_inference_workers: 2
        overlap_rollouts_and_learn: false
      auxiliary_losses: {}
bc:
  desc: null
  value:
    teacher_ckpt: ckpts/uLHP.300.pth
    writer: wb
    dtg_threshold: 1.0
    epochs: 1000
    batch_size: 2
    lr: 2.5e-05
    ckpt_freq: 100
    ckpt_folder: experiments/lmnav_imagenav/
_wandb:
  desc: null
  value:
    python_version: 3.9.17
    cli_version: 0.15.9
    framework: huggingface
    huggingface_version: 4.28.0
    is_jupyter_run: false
    is_kaggle_kernel: false
    start_time: 1693860293.965937
    t:
      1:
      - 1
      - 11
      - 41
      - 49
      - 50
      - 55
      - 63
      - 71
      - 105
      2:
      - 1
      - 11
      - 41
      - 49
      - 50
      - 55
      - 63
      - 71
      - 105
      3:
      - 13
      - 16
      - 23
      4: 3.9.17
      5: 0.15.9
      6: 4.28.0
      8:
      - 5
