# @package _global_

defaults:
  - /benchmark/nav/imagenav/imagenav_base
  - /exp: base
  - /logger@exp.logger: console  
  - /generator: base
  - /actor@generator.actor: old_eai_policy
  - /generator/filter_method: dtg
  - /dataset/imagenav: hm3d
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /habitat_baselines/rl/policy/obs_transforms:
    - resize_shortest_edge_base 
  - _self_

exp:
  name: "offline_744"
  root_dir: "data/datasets/lmnav"
  logger:
    project: "lmnav"
    name: "lmnav imagenav env 744 datagen"
    group: "datagen"
  
generator:
  num_episodes: 100000
  artifact: "offline_test"
  deterministic: False
  filter_method:
    dtg_threshold: 1.0
    
  actor:
    name: "actors.old_eai_policy"
    ckpt: "ckpts/uLHP.300.pth"

habitat_baselines:
  num_environments: 2
  rl:
    policy:
      obs_transforms:
        resize_shortest_edge:
          size: 120
          trans_keys: [rgb, depth, imagegoal]
    ddppo:
      distrib_backend: "NCCL" 
        
        
habitat:
  environment:
    max_episode_steps: 500
  simulator:
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
          depth_sensor:
            width: 640
            height: 480
    agents_order: ['main_agent']
    habitat_sim_v0:
      allow_sliding: false
  dataset:
    content_scenes: ['00744-1S7LAXRdDqK']

