defaults:
  - base_nav_llama@
  - /models/vis_encoder@vis_encoder: qformer
    
_target_: "lmnav.models.nav_llama.NavLLAMA"

freeze_llama_proj: False
low_resource: False

vis_encoder:
  freeze_backbone: True
  freeze_qformer: True
  vis_processor:
    _target_: "alpro_video_train"
    image_size: 224
    n_frms: 8
  
