# @package _global_

defaults:
  - /benchmark/nav/imagenav/imagenav_base
  - /habitat_baselines: habitat_baselines_rl_config_base
  - /habitat/dataset/imagenav: hm3d
  - /habitat_baselines/rl/policy/obs_transforms:
    - resize_shortest_edge_base
  - _self_

habitat_baselines:
  num_environments: 2
  rl:
    policy:
      obs_transforms:
        resize_shortest_edge:
          size: 120
          trans_keys: [rgb, depth, imagegoal]

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
          depth_sensor:
            width: 640
            height: 480
  dataset:
    content_scenes: ['00744-1S7LAXRdDqK']

