# @package _global_

defaults:
  - /benchmark/nav/imagenav/imagenav_base
  - /habitat/dataset/imagenav: hm3d
  - _self_

habitat:
  environment:
    max_episode_steps: 1000
  simulator:
    turn_angle: 30
    agents:
      main_agent:
        sim_sensors:
          rgb_sensor:
            width: 640
            height: 480
          depth_sensor:
            width: 640
            height: 480
  dataset:
    content_scenes: ['00744-1S7LAXRdDqK']

