defaults:
  - base_nav_llama@
    
_target_: "nav_llama"
freeze_vit: True
freeze_qformer: True
freeze_lora: True
freeze_qformer_compression: False
freeze_llama_proj: False
  
low_resource: False
  
qformer_compressor_cfg:
  num_latents: 4
  depth: 1
  self_per_cross_attn: 2
  cross_heads: 1
  latent_heads: 8
  cross_dim_head: 64
  latent_dim_head: 64

vis_processor:
  _target_: "alpro_video_train"
  image_size: 224
  n_frms: 8
  
